#!/bin/bash

# Script position
SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")

# Color table
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "[${YELLOW}Warning${NC}] This script will install a root service in your distribution that will start at startup. If you want to prevent that from happening, you should not continue this procedure."
echo -e "[${YELLOW}Warning${NC}] This script will create a highly vulnerable service. The autogenerated RUN.SH file will be protected agains writes BUT the executed python files will not, thus an expert hacker can easily leverage on that to obtain ROOT privileges! [Press Space to continue]"
read

# Check Root 
echo -e "[${GREEN}Info${NC}] Root access verification"
if [ "$EUID" -ne 0 ]
    then echo -e "[${RED}Error${NC}] This script needs root access to install some Python dependencies and the service itself"
    exit
fi

# Stop previous services
echo -e "[${GREEN}Info${NC}] Stopping identical services (if present)"
sudo systemctl stop binance.service

# Install python
echo -e "[${GREEN}Info${NC}] Installing Python3"
sudo apt update
sudo apt install python3 -y

# Install python-pip
echo -e "[${GREEN}Info${NC}] Installing Python3-pip"
sudo apt install python3-pip -y

# Install python packages
echo -e "[${GREEN}Info${NC}] Installing Binance connector dependencies"
sudo pip3 install python-binance
sudo pip3 install binance-connector

RUN_FILE_NAME="${SCRIPT_PATH}/run.sh"
RUN_FILE="\"${SCRIPT_PATH}/src/automatic_invester.py\""

# Remove previous run file
echo -e "[${GREEN}Info${NC}] Removing previous run file (if present)"
rm "${RUN_FILE_NAME}"

# Create run.sh file
echo -e "[${GREEN}Info${NC}] Creating the running shell file"
echo -e "#!/bin/bash\n\n/bin/python3 ${RUN_FILE}">run.sh

# Set the execute only priviledges
chmod 555 "${RUN_FILE_NAME}"

# Remove previous automatic running services under the same name
echo -e "[${GREEN}Info${NC}] Removing previous identical services (if present)"
sudo rm /etc/systemd/system/binance.service

# Create the automatically running service
echo -e "[${GREEN}Info${NC}] Creating the service file in /etc/systemd/system/binance.service"

SERVICE_FILE_NAME="/etc/systemd/system/binance.service"
echo -e "[Unit]\nDescription=BinanceAutomaticInvester\nAfter=network.target\n[Service]\nExecStart=\"${RUN_FILE_NAME}\"\n[Install]\nWantedBy=default.target">/etc/systemd/system/binance.service

# Final instructions
echo -e "[${GREEN}Info${NC}] Success!"
echo "---------------------------------------------------------------------------"
echo -e "\nTo run the service for the first time please type:\nsudo systemctl start binance.service && sudo systemctl enable binance.service"